// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKSzvqg0sG-nM3WA3tmDbNdm-GnobPaOQ',
    appId: '1:440104668695:web:36993c5604cbaf65789652',
    messagingSenderId: '440104668695',
    projectId: 'wilson-wings',
    authDomain: 'wilson-wings.firebaseapp.com',
    databaseURL: 'https://wilson-wings-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wilson-wings.appspot.com',
    measurementId: 'G-XVY0JH0N73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQv33qDk2p7Iz1Pmgd1NHoLTGWdOszk08',
    appId: '1:440104668695:android:6b94b4267f6172ce789652',
    messagingSenderId: '440104668695',
    projectId: 'wilson-wings',
    databaseURL: 'https://wilson-wings-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wilson-wings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKCi0x6bkz3VF3WQSU8_kxHVNbgCoNAyc',
    appId: '1:440104668695:ios:bdd21231c7d09b6c789652',
    messagingSenderId: '440104668695',
    projectId: 'wilson-wings',
    databaseURL: 'https://wilson-wings-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wilson-wings.appspot.com',
    iosClientId: '440104668695-8gih3hdce39rmc1860ajcptt9g1hb0vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.wilsonWings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKCi0x6bkz3VF3WQSU8_kxHVNbgCoNAyc',
    appId: '1:440104668695:ios:bdd21231c7d09b6c789652',
    messagingSenderId: '440104668695',
    projectId: 'wilson-wings',
    databaseURL: 'https://wilson-wings-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wilson-wings.appspot.com',
    iosClientId: '440104668695-8gih3hdce39rmc1860ajcptt9g1hb0vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.wilsonWings',
  );
}
